### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by davshoward** [kichik/dropbox-ignorer#1]
This looks extremely useful but I'm unsure how to run/use it? 

I'm on Windows.

**Comment by kichik** [comment]
All you need is to run the following from the command line:
```
dropbox-ignorer node_modules
```

**Comment by davshoward** [comment]
Ah - then I'm not clear on how to install it 🙄

**Comment by kichik** [comment]
It's a single executable. Nothing to install.
1. Extract it
2. Open command prompt or terminal
3. Drag executable to terminal window to paste its path
4. Add `node_modules` to the command and hit enter

**Comment by davshoward** [comment]
Great - thanks :-)
